[package]
name = "chess-gamesetup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2"
chess-ai = { path = "../chess-ai" }
chess-gui = { path = "../chess-gui" }
ggez = "0.7"
